"""Vizuelni stil po korisnikovoj referenci master_rad_interaktivno.html."""

HEADER = '''<div id="readingProgress" aria-hidden="true"></div>
<div class="studio-bar" aria-label="Kontrole animacija"><span class="studio-label">VIZUELNA LABORATORIJA</span><button id="studioPause" aria-pressed="false">Pauziraj animacije</button><label for="studioSpeed">Brzina</label><select id="studioSpeed"><option value="0.5">0,5×</option><option value="1" selected>1×</option><option value="2">2×</option></select><span class="studio-hint">Razumij korak. Pomjeri kontrolu. Pogledaj rezultat.</span></div>
<div class="studio-hero"><div class="studio-canvas-card"><div class="studio-card-top"><span>JEDAN SIGNAL · ČETIRI KORAKA</span><span class="studio-live">JavaScript / Canvas</span></div><canvas id="studioCanvas" role="img" aria-label="Animirana šema: ventilator, PCM talas, FFT spektar i odluka">Zvuk ventilatora → PCM uzorci → FFT spektar → provjera i odluka.</canvas><p class="caption">Šematski tok. Animacija pokazuje put podataka; nije mjerenje ventilatora niti simulacija vremena alarma.</p></div><div class="studio-stats"><div><strong>16 kHz</strong><span>16000 uzoraka u sekundi</span></div><div><strong>8192</strong><span>uzorka u jednom FFT segmentu</span></div><div><strong>1,953 Hz</strong><span>razmak susjednih binova</span></div><div><strong>96</strong><span>brojeva koji opisuju zvuk</span></div></div></div>'''

CSS = '''
:root{--ink:#edf6ff;--muted:#a1b7ca;--line:#294157;--accent:#66d9ff;--paper:#101e2c;--bg:#081018;--orange:#ffd479}
body{background:radial-gradient(ellipse at 45% 0,#19395466,transparent 32%),#081018;color:var(--ink);font-size:16px;line-height:1.8}
aside{background:#07111bec;border-right:1px solid #274058;backdrop-filter:blur(18px);width:270px;padding:32px 18px}
aside .brand{font-size:26px;letter-spacing:-1px;color:#e8f6ff}aside a{border:0;border-radius:10px;padding:9px 11px;margin:2px 0;color:#9eb2c6;font-size:12px}aside a:hover,aside a.active{background:#162c40;color:#edf6ff}aside a.active{box-shadow:inset 3px 0 #66d9ff}aside small{font-size:12px;color:#829eb6}
main{max-width:1250px;margin-left:270px;padding:34px 42px 100px;min-width:0}header{padding:25px 0 40px}h1{font-size:clamp(40px,5vw,70px);letter-spacing:-.055em;line-height:1.04;margin:22px 0;color:#f2f9ff}header>p:not(.tag){max-width:850px;color:#adc3d7}.tag{color:#79dfff;font-size:11px;letter-spacing:2.5px}h2{font-size:clamp(25px,3vw,37px);letter-spacing:-1px}h3{font-size:22px;letter-spacing:-.4px}a{color:#8ce2ff}
section{padding:34px;border:1px solid #253f54;background:linear-gradient(160deg,#112333d9,#0b1926f2);border-radius:22px;margin-bottom:42px;box-shadow:0 15px 50px #00000016;scroll-margin-top:95px}section:target{border-color:#537d99}section>p,section>ol,section>ul{color:#c3d3e1}strong{color:#eef8ff}code{background:#081622;color:#bae4f6;padding:3px 5px}pre{background:#060f19;border:1px solid #233d51;color:#c8e6f4;padding:23px;font-size:13px;line-height:1.8}.source{background:#091723;border-color:#29465d;border-radius:13px;padding:13px 17px}.source summary{color:#a4def2}.source p{color:#91abc0}
th{background:#152a3c;color:#9ed6ed}td{color:#bdcede}th,td{border-color:#284257}button,select{background:#10263a;color:#e8f4ff;border-color:#35556d;border-radius:10px;padding:9px 13px;font-size:14px;transition:background .18s,border-color .18s}button:hover{background:#1b3c55;border-color:#66d9ff}button:disabled{opacity:.38;cursor:default}input[type=range]{accent-color:#66d9ff;width:min(360px,100%)}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #ffd479;outline-offset:4px}
.lab{background:linear-gradient(160deg,#132b3e,#0c1b2a);border:1px solid #35556d;border-radius:19px;padding:25px;margin:28px 0;position:relative;overflow:hidden}.lab h3{color:#f0f9ff;margin-top:0;padding-right:65px}.lab>p{color:#bbcede}.lab .caption{font-size:12px;color:#8eaac0;line-height:1.65}.lab svg,.visual-lesson svg{background:#081521;border:1px solid #233e54;border-radius:14px;padding:10px;margin:22px 0}svg text{fill:#b8d0e3!important}.lab .buttons{gap:9px;padding:12px;background:#091927;border:1px solid #274357;border-radius:13px}.visual-lesson button[aria-pressed=true]{background:#164d68;border-color:#6fdbff;color:white}.lesson-readout{background:#0a2030!important;border-left-color:#66d9ff;border-radius:0 12px 12px 0;padding:16px 18px;color:#d6edfb!important;min-height:4em}.remember{background:#102c29!important;border:1px solid #285749;color:#bae5d2!important;border-radius:12px;padding:15px 18px}.flow span{background:#133343;color:#a5eaff;border:1px solid #2e586c}.flow b{color:#b894ff}.history span{background:#163b3a;color:#b9e7d1}.history .warn{background:#423318;color:#ffe1a1}.history .alarm{background:#45242b;color:#ffb9be}
#readingProgress{position:fixed;inset:0 auto auto 0;height:3px;width:0;background:linear-gradient(90deg,#66d9ff,#b894ff);z-index:110;box-shadow:0 0 16px #66d9ff77}.studio-bar{position:sticky;top:0;z-index:35;display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:12px 16px;background:#081622f5;border:1px solid #2a465d;border-radius:13px;backdrop-filter:blur(18px);margin:24px 0}.studio-label{font-size:10px;color:#8bdfff;letter-spacing:1.5px;margin-right:auto}.studio-bar label,.studio-hint{font-size:11px;color:#8da9be}.studio-hint{flex-basis:100%}.studio-hero{display:grid;grid-template-columns:minmax(0,1fr) 185px;gap:16px;margin:22px 0 36px}.studio-canvas-card{min-width:0;background:linear-gradient(145deg,#122a3e,#081723);border:1px solid #35546b;border-radius:20px;overflow:hidden;box-shadow:0 20px 60px #0003}.studio-card-top{display:flex;justify-content:space-between;gap:10px;padding:18px 20px;color:#a3cce5;font-size:10px;letter-spacing:1px}.studio-live{color:#92ddb5}#studioCanvas{display:block;width:100%;height:260px}.studio-canvas-card .caption{padding:0 20px 16px;font-size:12px;color:#91aabe;margin:0}.studio-stats{display:grid;grid-template-rows:repeat(4,1fr);gap:9px}.studio-stats>div{background:#0d2030;border:1px solid #29475d;border-radius:15px;padding:13px 16px}.studio-stats strong{display:block;font-size:25px;line-height:1.3;letter-spacing:-1px;color:#b6eaff}.studio-stats span{display:block;font-size:11px;color:#90aabe;margin-top:4px}.focus-lab{position:absolute;right:14px;top:14px;font-size:11px;padding:6px 10px;z-index:2}.lab.is-focused{position:fixed;inset:18px;margin:0;z-index:100;overflow:auto;box-shadow:0 0 0 100vw #030911ee;border-color:#5d8caa;padding:32px max(25px,calc((100vw - 1160px)/2));border-radius:20px}.lab.is-focused svg{max-height:62vh;min-height:260px}.focus-open{overflow:hidden}
@media(min-width:1550px){main{margin-left:calc(270px + (100vw - 1520px)/2)}}
@media(max-width:1000px){aside{position:static;width:auto;max-height:270px}main{margin:0;padding:24px}.studio-hero{grid-template-columns:1fr}.studio-stats{grid-template-columns:repeat(4,1fr);grid-template-rows:1fr}.studio-stats strong{font-size:22px}.lab{padding:20px}}
@media(max-width:580px){main{padding:12px}section{padding:20px 15px;border-radius:17px}.lab{padding:17px 12px}.lab h3{font-size:20px}.lab svg{padding:2px;min-height:200px}.studio-stats{grid-template-columns:1fr 1fr}.studio-bar{gap:7px;padding:10px}.studio-label{flex-basis:100%}.studio-hint{display:none}#studioCanvas{height:225px}.lab.is-focused{inset:6px;padding:28px 12px}.lab.is-focused svg{min-height:180px}.lab .buttons{padding:9px}.studio-card-top{font-size:9px}.studio-live{display:none}}
@media print{.studio-bar,.focus-lab,#readingProgress,.studio-hero{display:none}body{background:white;color:#183239}main{margin:0;padding:0}section,.lab{background:white;box-shadow:none;border-color:#bbb;color:#183239}section>p,section>ol,section>ul,.lab>p,strong,h1,h2,h3,td{color:#183239!important}.lab svg{background:#081521;print-color-adjust:exact}.lesson-readout,.remember{background:#eef4f1!important;color:#183239!important}pre{background:#f2f5f5;color:#183239}code{background:#eef3f3;color:#183239}.source{background:white}a{color:#183239}}
'''

JS = r'''
// SVG ostaje oštar pri uvećanju; Canvas je za kontinuiranu animaciju uvoda.
function studioColor(value){const colors={'#087e8b':'#66d9ff','#086d78':'#66d9ff','#bb5e17':'#ffd479','#af3c27':'#ff929f','#183239':'#cbe8ff','#344f57':'#b8d0e3','#398b77':'#7ee2a8','#546b72':'#91afc7','#697e83':'#819caf','#7d9ba0':'#66859e','#a9baba':'#6e8ba0','#adb8b8':'#607e94','#afc7c8':'#55778f','#b5c9c4':'#29495e','#b6c7c3':'#42637b','#cee9e0':'#123b40','#d5eae4':'#163549','#d8ede4':'#173d48','#e5ebe1':'#1d3048','#edf1f0':'#132738','#eff7f4':'#0c1b29','#e0e9e6':'#1e3548'};return colors[String(value).toLowerCase()]||value}
document.querySelectorAll('.lab svg [fill],.lab svg [stroke]').forEach(e=>{for(const a of ['fill','stroke']){const value=e.getAttribute(a);if(value)e.setAttribute(a,studioColor(value))}});
let focusedLab=null,focusTrigger=null;
function closeLabFocus(){if(!focusedLab)return;focusedLab.classList.remove('is-focused');document.body.classList.remove('focus-open');focusTrigger.textContent='Uvećaj';focusTrigger.setAttribute('aria-expanded','false');const trigger=focusTrigger;focusedLab=null;focusTrigger=null;trigger.focus()}
document.querySelectorAll('.lab').forEach(lab=>{const b=document.createElement('button');b.className='focus-lab';b.textContent='Uvećaj';b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Uvećaj ilustraciju');b.addEventListener('click',()=>{if(focusedLab===lab){closeLabFocus();return}closeLabFocus();focusedLab=lab;focusTrigger=b;lab.classList.add('is-focused');document.body.classList.add('focus-open');b.textContent='Zatvori';b.setAttribute('aria-expanded','true');b.focus()});lab.prepend(b)});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeLabFocus();if(event.key==='Tab'&&focusedLab){const items=[...focusedLab.querySelectorAll('button:not(:disabled),input,select,a[href]')];if(event.shiftKey&&document.activeElement===items[0]){event.preventDefault();items.at(-1).focus()}else if(!event.shiftKey&&document.activeElement===items.at(-1)){event.preventDefault();items[0].focus()}}});
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
let studioPaused=motionPreference.matches,studioRate=1,studioTime=0,studioLast=0,heroVisible=true;
function updateStudioPause(){const b=$('studioPause');b.textContent=studioPaused?'Nastavi animacije':'Pauziraj animacije';b.setAttribute('aria-pressed',String(studioPaused))}
$('studioPause').addEventListener('click',()=>{studioPaused=!studioPaused;updateStudioPause()});$('studioSpeed').addEventListener('change',()=>studioRate=+$('studioSpeed').value);updateStudioPause();
motionPreference.addEventListener('change',event=>{if(event.matches){studioPaused=true;updateStudioPause()}});
function updateReading(){const max=document.documentElement.scrollHeight-window.innerHeight;$('readingProgress').style.width=(max>0?window.scrollY/max*100:0)+'%'}window.addEventListener('scroll',updateReading,{passive:true});updateReading();
if(typeof IntersectionObserver!=='undefined'){const navObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)document.querySelectorAll('aside nav a').forEach(a=>{const active=a.getAttribute('href')==='#'+e.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})},{rootMargin:'-12% 0px -65% 0px'});document.querySelectorAll('main>section').forEach(s=>navObserver.observe(s));new IntersectionObserver(es=>heroVisible=es[0].isIntersecting).observe($('studioCanvas'))}
const heroCanvas=$('studioCanvas'),heroCtx=heroCanvas.getContext('2d');let heroWidth=0,heroHeight=0;
function sizeStudio(){const r=heroCanvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);heroWidth=r.width;heroHeight=r.height;heroCanvas.width=Math.round(r.width*dpr);heroCanvas.height=Math.round(r.height*dpr);heroCtx.setTransform(dpr,0,0,dpr,0,0);drawStudio(studioTime)}
function drawStudio(t){const c=heroCtx,w=heroWidth,h=heroHeight;if(!w)return;c.clearRect(0,0,w,h);const colors=['#66d9ff','#b894ff','#7ee2a8','#ffd479'],labels=['Zvuk','PCM','FFT','Odluka'],centers=[.13,.38,.63,.88].map(x=>x*w),cy=h*.48,scale=Math.min(w/650,1);c.strokeStyle='#213e53';c.lineWidth=1;for(let x=20;x<w;x+=32){c.beginPath();c.moveTo(x,35);c.lineTo(x,h-35);c.stroke()}c.strokeStyle='#35576e';c.beginPath();c.moveTo(centers[0],cy);c.lineTo(centers[3],cy);c.stroke();for(let i=0;i<4;i++){const x=centers[i];c.fillStyle='#0a1b29';c.beginPath();c.arc(x,cy,42*scale,0,Math.PI*2);c.fill();c.strokeStyle=colors[i]+'88';c.stroke();c.font=`600 ${Math.max(11,14*scale)}px system-ui`;c.textAlign='center';c.fillStyle=colors[i];c.fillText(labels[i],x,cy+66*scale);c.fillStyle='#90abc0';c.font='10px system-ui';c.fillText(['rotacija','uzorci','frekvencije','provjere'][i],x,cy+85*scale)}
 c.save();c.translate(centers[0],cy);c.rotate(t*.8);for(let i=0;i<5;i++){c.rotate(2*Math.PI/5);c.fillStyle='#66d9ff66';c.beginPath();c.moveTo(0,0);c.quadraticCurveTo(32*scale,-9*scale,25*scale,18*scale);c.quadraticCurveTo(8*scale,20*scale,0,0);c.fill()}c.fillStyle='#a8efff';c.beginPath();c.arc(0,0,5*scale,0,Math.PI*2);c.fill();c.restore();
 c.strokeStyle='#b894ff';c.lineWidth=2;c.beginPath();for(let i=0;i<=70;i++){const x=centers[1]-32*scale+i/70*64*scale,y=cy-Math.sin(i/70*4*Math.PI-t*2)*15*scale;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();for(let i=0;i<11;i++){const x=centers[2]-28*scale+i*5.6*scale,amp=(4+24*Math.exp(-(((i-3)/1.4)**2))+17*Math.exp(-(((i-8)/1.2)**2)))*scale;c.strokeStyle='#7ee2a8';c.beginPath();c.moveTo(x,cy+20*scale);c.lineTo(x,cy+20*scale-amp);c.stroke()}
 for(let i=0;i<3;i++){c.fillStyle=i<=Math.floor(t%6/2)?'#ffd479':'#3d3d35';c.beginPath();c.arc(centers[3]+(i-1)*14*scale,cy,4.5*scale,0,Math.PI*2);c.fill()}const phase=(t%8)/8*3,idx=Math.floor(phase),u=phase-idx,x=centers[idx]*(1-u)+centers[Math.min(idx+1,3)]*u;c.shadowBlur=15;c.shadowColor='#8de5ff';c.fillStyle='#dcf8ff';c.beginPath();c.arc(x,cy-47*scale,4,0,Math.PI*2);c.fill();c.shadowBlur=0;
}
// Jedan vremenski raspored za sve animacije. Ne radi račun za skrivene lekcije.
function studioFrame(now){const dt=studioLast?Math.min((now-studioLast)/1000,.1):0;studioLast=now;if(!studioPaused&&!document.hidden){studioTime+=dt*studioRate;for(const [id,job]of lessonTimers){const lab=$(id).closest('.lab');if(lab){const r=lab.getBoundingClientRect();if(r.bottom<0||r.top>window.innerHeight)continue}job.elapsed+=dt*1000*studioRate;if(job.elapsed>=job.ms){job.elapsed%=job.ms;job.step()}}if(heroVisible)drawStudio(studioTime)}requestAnimationFrame(studioFrame)}
new ResizeObserver(sizeStudio).observe(heroCanvas);sizeStudio();requestAnimationFrame(studioFrame);
'''
